# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):

- The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
- The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).


In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [5]:
# Import torch
import torch

# Create random tensor
tensor_A = torch.rand(size=(7, 7))
tensor_A

tensor([[0.9824, 0.4624, 0.1938, 0.5330, 0.2737, 0.7902, 0.9064],
        [0.6148, 0.6656, 0.7728, 0.2317, 0.9271, 0.4770, 0.6918],
        [0.1381, 0.0259, 0.5930, 0.8315, 0.5049, 0.6868, 0.7898],
        [0.7367, 0.1473, 0.0321, 0.4364, 0.7425, 0.1156, 0.1091],
        [0.5709, 0.9597, 0.6227, 0.0563, 0.3539, 0.7068, 0.4590],
        [0.2299, 0.7764, 0.4806, 0.2774, 0.8070, 0.0292, 0.3213],
        [0.1944, 0.4316, 0.2191, 0.8114, 0.7713, 0.6234, 0.6976]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).


In [ ]:
# Create another random tensor
tensor_B = torch.rand(size=(1, 7))

# Perform matrix multiplication
# We need to transpose tensor_B to make shapes compatible: (7, 7) @ (7, 1)
tensor_C = torch.matmul(tensor_A, tensor_B.T)
print(tensor_C, tensor_C.shape)

tensor([[2.8026],
        [2.7619],
        [2.0655],
        [1.5646],
        [2.4006],
        [1.8913],
        [2.3618]]) torch.Size([7, 1])


### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:

```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```


In [8]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
tensor_D = torch.rand(size=(7, 7))
tensor_E = torch.rand(size=(1, 7))

# Matrix multiply tensors
tensor_F = torch.matmul(tensor_D, tensor_E.T)
print(tensor_F, tensor_F.shape)

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]]) torch.Size([7, 1])


### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)

- If there is, set the GPU random seed to `1234`.


In [9]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)

### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```


In [10]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Device: {device}")

# Create two random tensors on GPU
tensor_G = torch.rand(size=(2, 3)).to(device)
tensor_H = torch.rand(size=(2, 3)).to(device)
print(tensor_G, tensor_H)

Device: cpu
tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]]) tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]])


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:

```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```


In [11]:
# Perform matmul on tensor_G and tensor_H
# We need to transpose tensor_H: (2, 3) @ (3, 2)
tensor_I = torch.matmul(tensor_G, tensor_H.T)
print(tensor_I, tensor_I.shape)

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]]) torch.Size([2, 2])


### 8. Find the maximum and minimum values of the output of 7.


In [12]:
# Find max
max_val = torch.max(tensor_I)
print(max_val)

# Find min
min_val = torch.min(tensor_I)
print(min_val)

tensor(0.5617)
tensor(0.3647)


### 9. Find the maximum and minimum index values of the output of 7.


In [13]:
# Find arg max (index of max value)
max_idx = torch.argmax(tensor_I)
print(max_idx)

# Find arg min (index of min value)
min_idx = torch.argmin(tensor_I)
print(min_idx)

tensor(3)
tensor(0)


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```


In [14]:
# Set seed
torch.manual_seed(7)

# Create random tensor
tensor_J = torch.rand(size=(1, 1, 1, 10))

# Remove single dimensions
tensor_K = torch.squeeze(tensor_J)

# Print out tensors and their shapes
print(tensor_J, tensor_J.shape)
print(tensor_K, tensor_K.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
